CREATE TABLE IF NOT EXISTS `e.sun_bank`.`seating_chart` (
  `FLOOR_SEAT_SEQ` INT NOT NULL AUTO_INCREMENT,
  `FLOOR_NO` INT NULL DEFAULT NULL,
  `SEAT_NO` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`FLOOR_SEAT_SEQ`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;
