CREATE TABLE IF NOT EXISTS `e.sun_bank`.`employee` (
  `EMP_ID` INT NOT NULL,
  `NAME` VARCHAR(45) NULL DEFAULT NULL,
  `EMAIL` VARCHAR(45) NULL DEFAULT NULL,
  `FLOOR_SEAT_SEQ` INT NULL DEFAULT '0',
  PRIMARY KEY (`EMP_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;